baseurl      = "/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 20


[params]
  [params.mermaid]
    js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.min.js'
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
 
  # enable Theme blink
  enableThemeToggle = true

  # Subtitle for home
  homeSubtitle = "Software Engineer // Consultant"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]
  

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "categorys"
    tag      = "tags"
    series      = "series"

[languages]
  [languages.en]
    title = "Hello Friend "
    subtitle = "A coder's Homepage"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "hello world..."
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

 [[params.social]]
  name = "twitter"
  url = "https://twitter.com/Jack29994233"
 [[params.social]]
  name = "email"
  url = "mailto:findstockgod@gmail.com"
 [[params.social]]
  name = "github"
  url = "https://github.com/wangweiomg"
 [[params.social]]
  name = "telegram"
  url = "https://t.me/technojones"


  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "categorys"
    name       = "Category"
    url        = "/categorys"
  [[menu.main]]
    identifier = "series"
    name       = "Series"
    url        = "/series"

